name: Run Integration Tests

on:
  push:
    branches:
      - main  # или другая ветка, на которую вы хотите запускать тесты
  pull_request:
    branches:
      - main  # или другая ветка, на которую вы хотите запускать тесты

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-golden

    - name: Run integration tests
      run: pytest src/integration_test.py  # Замените на путь к вашему тестовому файлу
    - name: Run prob test
      run: pytest src/prob_test.py
